### ISSUE TITLE
Joining Jazzband

### ISSUE THREAD

**Issue by hendrikschneider** [jazzband/django-fernet-encrypted-fields#7]
Hi, 

I stumbled accross your repository while looking for a way to encrypt a model field. I was glad to find one that is maintained, which seems to be a huge problem with model encryption django apps.

As encryption apps are crucial for some applications and cannot be easily replaced, it would be nice to have one model encryption app joining Django Jazzband [https://jazzband.co/] to make sure it will also be well maintained in the future.

**Comment by frgmt** [comment]
@hendrikschneider I am very honored to hear that. Of course I would be happy to participate.

**Comment by frgmt** [comment]
I tried👍  https://github.com/jazzband/help/issues/282

**Comment by hendrikschneider** [comment]
That's awesome. I will see if I manage to setup some github actions for the repository.

**Comment by StevenMapes** [comment]
Both would be great, I didn't get around to looking to setup GitHub actions when I made my PRs. Do we also look at moving the project to use [Black](https://black.readthedocs.io/en/stable/) for code formatting since it's becoming more and more a defacto now and Django itself [moved to that from 4.0.3](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/#python-style)?

**Comment by frgmt** [comment]
Nice. Normally I'm using Black too.

**Comment by hendrikschneider** [comment]
I am also using it. I will add black to the github actions

**Comment by StevenMapes** [comment]
Whilst you're doing that would you mine editing line 156 of package_test.tests.py please as I just realised I put a typo in the comment and it feels like a weak PR to just change that if you are working on more changes ;)

**Comment by hendrikschneider** [comment]
I've fixed the typo and created a PR with linting, testing and coverage.

Should the code be tested on each push or only prs?

Is Coverage using Codecov fine for you?

**Comment by StevenMapes** [comment]
I'm just a contributor but my two cents are:

1. **Tests on push or only on PR?** 
This is up to @frgmt as they are the only one with access to push directly. All mine contributions have been PR's.  Personally I'd vote for "all push and PRs" to help catch and issues sooner.
2. **Coverage** - CodeCov is fine with me, as long as it has coverage but again up to @frgmt

*Additional thought / discussion point*
The project supports Django 2.2+ so  tests should really cover Django 2.2 through 4.0.* along side Python 3.7 through 3.10.

Is it worth getting ahead of things and also adding in a test for Django 3.2 and 4.0 with Python 3.11-alpha? I've done that with some of my own internal libs mainly to check for future issues. If it fails I've then disabled the test and added an issue to look at it later, but it if passes then it'll be worth keeping in to help keep the project on track for it's eventual release

**Comment by frgmt** [comment]
I think "all push and PRs" and CodeCov are fine.
You guys don't have to worry about me, especially if we are joining a jazzband.

**Comment by whyscream** [comment]
How is this working out? When reading the [Jazzband guidelines](https://jazzband.co/about/guidelines), I don't think the [linked open issue](https://github.com/jazzband/help/issues/282) in the jazzband repo will work. Agreeing that a properly and easily maintained package for django encrypted model fields would e really nice. +1 for jazzband

**Comment by frgmt** [comment]
Successful transition to jazzband 👍
